// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://anghplqtuhnmflbmgofm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFuZ2hwbHF0dWhubWZsYm1nb2ZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMzEzNTIsImV4cCI6MjA2OTkwNzM1Mn0.cL9Uhd-fmEOQX6pCZHUvae864nIQJQidit0CF93EOr4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});